"use client";

import { useState } from "react";
import {
  BarChart3,
  TrendingUp,
  Download,
  Calendar,
  DollarSign,
  Users,
  CheckCircle2,
  Star,
  Award,
  Sparkles,
  ArrowUpRight,
  ShieldCheck,
} from "lucide-react";
import { toast } from "sonner";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { StatCard } from "@/components/cards/stat-card";
import { formatCurrency, getAvatarUrl, getInitials } from "@/utils/format";
import { useAdminStats, useCategories } from "@/hooks";

export default function AdminReportsPage() {
  const { data: statsRes } = useAdminStats();
  const { data: categoriesRes } = useCategories();

  const [isExporting, setIsExporting] = useState(false);

  const stats = statsRes?.data;
  const categories = categoriesRes?.data ?? [];

  const handleExport = () => {
    setIsExporting(true);
    setTimeout(() => {
      setIsExporting(false);
      toast.success("Platform financial report exported to CSV successfully!");
    }, 1000);
  };

  const topTechnicians = [
    { name: "Kamal Hossain", specialty: "Electrical", rating: 4.9, jobs: 48, revenue: 145000 },
    { name: "Sumon Das", specialty: "Plumbing", rating: 4.8, jobs: 42, revenue: 128000 },
    { name: "Rafiqul Islam", specialty: "AC Repair", rating: 4.8, jobs: 39, revenue: 115000 },
    { name: "Nayeem Ahmed", specialty: "Carpentry", rating: 4.7, jobs: 31, revenue: 95000 },
  ];

  const categoryPerformance = [
    { name: "Plumbing & Sanitary", percentage: 38, count: 320, revenue: 480000 },
    { name: "Electrical & Wiring", percentage: 28, count: 245, revenue: 390000 },
    { name: "AC & Refrigeration", percentage: 20, count: 180, revenue: 320000 },
    { name: "Appliance Repair", percentage: 14, count: 110, revenue: 160000 },
  ];

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-neutral-900 dark:text-white sm:text-3xl">
            Reports & Platform Analytics
          </h1>
          <p className="text-sm text-neutral-500 dark:text-neutral-400">
            Marketplace revenue analytics, category performance, and top technician rankings.
          </p>
        </div>
        <Button
          onClick={handleExport}
          className="gap-2 bg-neutral-900 hover:bg-neutral-800 text-white font-semibold dark:bg-neutral-100 dark:text-neutral-900 dark:hover:bg-white"
        >
          <Download className="size-4" /> Export Report (CSV)
        </Button>
      </div>

      {/* Top Metrics */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          icon={TrendingUp}
          label="Total Marketplace GMV"
          value={formatCurrency(stats?.totalRevenue || 1250000)}
          iconColor="text-emerald-600"
          iconBg="bg-emerald-100 dark:bg-emerald-900/30"
          trend={{ value: 24, isPositive: true }}
        />
        <StatCard
          icon={DollarSign}
          label="Platform Net Revenue (10%)"
          value={formatCurrency(Math.round((stats?.totalRevenue || 1250000) * 0.1))}
          iconColor="text-blue-600"
          iconBg="bg-blue-100 dark:bg-blue-900/30"
          trend={{ value: 18, isPositive: true }}
        />
        <StatCard
          icon={CheckCircle2}
          label="Job Completion Rate"
          value="96.4%"
          iconColor="text-purple-600"
          iconBg="bg-purple-100 dark:bg-purple-900/30"
        />
        <StatCard
          icon={Users}
          label="Monthly Active Users"
          value="1,840"
          iconColor="text-amber-600"
          iconBg="bg-amber-100 dark:bg-amber-900/30"
          trend={{ value: 12, isPositive: true }}
        />
      </div>

      {/* Two Column Section: Category Distribution & Top Performers */}
      <div className="grid gap-6 lg:grid-cols-2">
        {/* Category Breakdown */}
        <Card className="border-neutral-200 dark:border-neutral-800">
          <CardHeader>
            <CardTitle className="text-lg font-bold">Category Booking Distribution</CardTitle>
            <CardDescription>
              Volume share and total GMV generated by service categories
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            {categoryPerformance.map((cat) => (
              <div key={cat.name} className="space-y-2">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-semibold text-neutral-900 dark:text-white">
                    {cat.name}
                  </span>
                  <div className="flex items-center gap-2">
                    <span className="text-neutral-500">{cat.count} jobs</span>
                    <strong className="text-neutral-900 dark:text-white">
                      {formatCurrency(cat.revenue)}
                    </strong>
                  </div>
                </div>
                <Progress value={cat.percentage} className="h-2 bg-neutral-100 dark:bg-neutral-800" />
              </div>
            ))}
          </CardContent>
        </Card>

        {/* Top Performing Technicians */}
        <Card className="border-neutral-200 dark:border-neutral-800">
          <CardHeader>
            <CardTitle className="text-lg font-bold">Top Performing Technicians</CardTitle>
            <CardDescription>
              Ranked by completed service jobs and customer satisfaction
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {topTechnicians.map((tech, index) => (
                <div
                  key={tech.name}
                  className="flex items-center justify-between rounded-lg border border-neutral-100 bg-neutral-50/50 p-3 dark:border-neutral-800 dark:bg-neutral-900/50"
                >
                  <div className="flex items-center gap-3">
                    <span className="flex size-6 items-center justify-center rounded-full bg-neutral-200 text-xs font-bold text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300">
                      {index + 1}
                    </span>
                    <Avatar className="size-9">
                      <AvatarImage src={getAvatarUrl(tech.name)} alt={tech.name} />
                      <AvatarFallback>{getInitials(tech.name)}</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-semibold text-neutral-900 dark:text-white text-sm">
                        {tech.name}
                      </p>
                      <p className="text-xs text-neutral-500">{tech.specialty}</p>
                    </div>
                  </div>

                  <div className="text-right">
                    <div className="flex items-center justify-end gap-1 text-amber-500 text-xs font-bold">
                      <Star className="size-3.5 fill-amber-400" />
                      <span>{tech.rating}</span>
                    </div>
                    <p className="text-xs text-neutral-500">{tech.jobs} jobs completed</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
